services:
  postgres:
    image: sidneygil/deckbuilder-db:v16-multiplatform
    container_name: deckbuilder-postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: deckbuilderdb
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - deckbuilder-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    ports:
      - "9400:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - deckbuilder-network
    restart: unless-stopped
    user: root

  eureka-server:
    build: ./eureka-server
    container_name: eureka-server
    ports:
      - "8761:8761"
    networks:
      - deckbuilder-network

  user-service:
    build: ./UserService
    container_name: user-service
    depends_on:
      - eureka-server
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/deckbuilderdb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: mysecretpassword
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka/
    ports:
      - "8082:8082"
    networks:
      - deckbuilder-network

  builder-service:
    build: ./BuilderService
    container_name: builder-service
    depends_on:
      - eureka-server
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/deckbuilderdb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: mysecretpassword
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka/
    ports:
      - "8081:8081"
    networks:
      - deckbuilder-network

  gateway:
    build: ./gateway
    container_name: gateway
    depends_on:
      - eureka-server
      - user-service
      - builder-service
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka/
    ports:
      - "8080:8080"
    networks:
      - deckbuilder-network

  frontend:
    build: ./Frontend
    container_name: deckbuilder-frontend
    depends_on:
      - builder-service
      - user-service
      - gateway
    ports:
      - "3000:80"
    networks:
      - deckbuilder-network
    environment:
      - NODE_ENV=production

volumes:
  postgres-data:
    driver: local
  jenkins_home:
    driver: local

networks:
  deckbuilder-network:
    driver: bridge
