server:
  port: 8080

spring:
  application:
    name: GATEWAY
  cloud:
    gateway:
      routes:
        - id: user-service-route
          uri: lb://USERSERVICE
          predicates:
            - Path=/users/**
          filters:
            - StripPrefix=1

        - id: builder-service-cards
          uri: lb://BUILDERSERVICE
          predicates:
            - Path=/card/**
        
        - id: builder-service-decks
          uri: lb://BUILDERSERVICE
          predicates:
            - Path=/deck/**
        
        - id: builder-service-deck-cards
          uri: lb://BUILDERSERVICE
          predicates:
            - Path=/deck-card/**
        
        - id: builder-service-sets
          uri: lb://BUILDERSERVICE
          predicates:
            - Path=/set/**

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    appname: GATEWAY
